{%- from 'zoomdata/map.jinja' import zoomdata with context -%}

######################################################################
# ATTENTION! Managed by SaltStack.                                   #
# DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN! #
######################################################################

{%- set environment = zoomdata.environment[service]['variables']|default({}, true) %}
{# blank line inserted here #}
{%- for key, value in environment|dictsort() %}
    {%- if value is none %}
        {%- set value = '' %}
    {%- endif %}
{{ key }}="{{ value }}"
{%- endfor %}

{#- vim: ft=jinja sw=4 sts=4 et
-#}
